#include <stdio.h>
#include <libft.h>

#include <locale.h>

#define EXPLICIT
#define SPECIFIERS
#define FLAGS
#define WIDTH
#define PRECISION
#define LENGTH
#define UNICODE
#define HEX
#define OCTAL
#define CHAR
#define DIGIT
#define UNSIGNED
#define NOSPEC
#define UNSPEC
#define HARDCORE
#define MOULITEST

#define PRINTF_TEST "printf_out.tmp"
#define FT_TEST "ft_out.tmp"
#define STD_OUT "/dev/tty"
#define BUFF_SIZE 1024

char	*to_str(int fd)
{
	char	buffer[BUFF_SIZE + 1];
	char	*str = NULL;
	int		bcount = 1;

	str = ft_strnew(1);
	while (bcount > 0)
	{
		bcount = read(fd, buffer, BUFF_SIZE);
		buffer[bcount] = '\0';
		str = ft_strjoin(str, buffer);
		//dprintf(2, "bcount: %i\n", bcount);
		//dprintf(2, "str: %s\n", str);
		//return (0);
	}
	return (str);
}

void	test(const char *format)
{
	FILE	*fd_std = NULL;
	FILE	*fd_ft = NULL;
	char	*str_std = NULL;
	char	*str_ft = NULL;
	int		ret_std = 0;
	int		ret_ft = 0;

	fd_std = freopen(PRINTF_TEST, "w+", stdout);
	ret_std = printf(format);
	rewind(fd_std);
	str_std = to_str(fileno(fd_std));
	freopen(STD_OUT, "w", stdout);
	//fclose(fd_std);
	fd_ft = freopen(FT_TEST, "w+", stdout);
	ret_ft = ft_printf(format);
	rewind(fd_ft);
	str_ft = to_str(fileno(fd_ft));
	freopen(STD_OUT, "w", stdout);
	//fclose(fd_ft);
	//printf("str_std: %s\n", str_std);
	//printf("str_ft: %s\n", str_ft);
	if (ft_strcmp(str_std, str_ft))
	{
		printf("[%s]: \x1B[31mOutput doesn't match\x1B[0m\n", format);
		printf("ft_: %s\n", str_ft);
		printf("std: %s\n", str_std);
	}
	else if (ret_ft != ret_std)
	{
		printf("[%s]: \x1B[33mReturns doesn't match [std: %i, ft: %i]\x1B[0m\n", format, ret_std, ret_ft);
	}
	else
		printf("[%s]: \x1B[32mOk\x1B[0m\n", format);

}

void	test_s(const char *format, const char *str)
{
	printf("[%s]\n", format);
	ft_putstr("std: ");
	printf(" (%i)\n", printf(format, str));
	ft_putstr("ft_: ");
	printf(" (%i)\n", ft_printf(format, str));
}

void	test_S(const char *format, const wchar_t *wstr)
{
	printf("[%s]\n", format);
	ft_putstr("std: ");
	printf(" (%i)\n", printf(format, wstr));
	ft_putstr("ft_: ");
	printf(" (%i)\n", ft_printf(format, wstr));
}

void	test_i(const char *format, int nb)
{
	printf("[%s]\n", format);
	ft_putstr("std: ");
	printf(" (%i)\n", printf(format, nb));
	ft_putstr("ft_: ");
	printf(" (%i)\n", ft_printf(format, nb));
}


int main(void)
{
	wchar_t	*wstr = L"a sample wide string";
	char	*str = "a sample string";
	int		nb = 42;

	(void)wstr;
	(void)str;
	(void)nb;
	// sS  string of characters
	// p   pointer address
	// dD  signed decimal integer
	// i   signed decimal integer
	// oO  unsigned octal
	// uU  unsigned decimal integer
	// xX  unsigned hexadecimal integer lowercase / uppercase
	// cC  character

	//printf("itoa: %i\nft_itoa: %i\n", itoa(44200), ft_itoa(44200));
	/*
	printf("intmax_t: %i\n", sizeof(intmax_t));
	printf("int64_t: %i\n", sizeof(int64_t));
	printf("int: %i\n", sizeof(int));
	printf("long int: %i\n", sizeof(long int));
	printf("long long int: %i\n", sizeof(long long int));
	*/

#ifdef EXPLICIT

# ifdef SPECIFIERS

	ft_putendl("=== %% ===");
	test("%%");
	test("%%i");
	test("%% is a percent symbol");
	return (0);
	ft_putendl("=== %s ===");
	test_s("%s", str);
	test_s("%s", "a constant string");
	test_s("%s", NULL);
	ft_putendl("=== %S ===");
	test_S("%S", wstr);
	test_S("%S", L"a constant wide string");
	test_S("%S", NULL);
	ft_putendl("=== %p ===");
	test_s("%p", str);
	test_s("%p", "constant");
	test_s("%p", NULL);
	ft_putendl("=== %d ===");
	test_i("%d", nb);
	ft_putendl("=== %D ===");
	test_i("%D", nb);
	ft_putendl("=== %i ===");

	ft_putendl("Specifier: %i");
	printf(" (%i)\n", printf("std: %i", nb));
	printf(" (%i)\n", ft_printf("ft_: %i", nb));
	printf(" (%i)\n", printf("std: %i is an int", nb));
	printf(" (%i)\n", ft_printf("ft_: %i is an int", nb));
	ft_putstr("\n");

	ft_putendl("Specifier: %o %O");
	printf(" (%i)\n", printf("std: %o", nb));
	printf(" (%i)\n", ft_printf("ft_: %o", nb));
	printf(" (%i)\n", printf("std: %O", nb));
	printf(" (%i)\n", ft_printf("ft_: %O", nb));
	ft_putstr("\n");

	ft_putendl("Specifier: %u %U");
	printf(" (%i)\n", printf("std: %u", nb));
	printf(" (%i)\n", ft_printf("ft_: %u", nb));
	printf(" (%i)\n", printf("std: %U", nb));
	printf(" (%i)\n", ft_printf("ft_: %U", nb));
	ft_putstr("\n");

	ft_putendl("Specifier: %x %X");
	printf(" (%i)\n", printf("std: %x", nb));
	printf(" (%i)\n", ft_printf("ft_: %x", nb));
	printf(" (%i)\n", printf("std: %X", nb));
	printf(" (%i)\n", ft_printf("ft_: %X", nb));
	ft_putstr("\n");

	ft_putendl("Specifier: %c");
	printf(" (%i)\n", printf("std: %c", nb));
	printf(" (%i)\n", ft_printf("ft_: %c", nb));
	ft_putstr("\n");
# endif
# ifdef FLAGS
	ft_putendl("Flag: -");
	printf(" (%i)\n", printf("std: %-i", nb));
	printf(" (%i)\n", ft_printf("ft_: %-i", nb));
	//ft_printf("ft_: %-i\n", nb);
	ft_putstr("\n");

	ft_putendl("Flag: +");
	ft_putendl("Specifier: %d %D");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%+d", nb));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%+d", nb));
	ft_putendl("Specifier: %i");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%-+-+d", nb));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%-+-+d", nb));
	ft_putstr("\n");
	ft_putendl("Flag: {space}");
	ft_putstr("std:");
	printf(" (%i)\n", printf("% i", nb));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("% i", nb));
	ft_putstr("\n");
	ft_putendl("Flag: #");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#x", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#x", 42));
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#X", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#X", 42));
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#o", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#o", 42));
	ft_putstr("std:");
	printf(" (%i)\n", printf("%-10s is a string", "this"));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#-10s is a string", "this"));
	ft_putstr("std:");
	printf(" (%i)\n", printf("%-.2s is a string", "this"));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#-.2s is a string", "this"));
	ft_putstr("std:");
	printf(" (%i)\n", printf("%-10s is a string", ""));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#-10s is a string", ""));
	ft_putstr("std:");
	printf(" (%i)\n", printf("%-5.2s is a string", ""));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#-5.2s is a string", ""));
# endif
# ifdef WIDTH
	ft_putendl("Width: printf(\"%5i\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%5i", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%5i", 42 ));
	ft_putstr("\n");
	ft_putendl("printf(\"%10s\" is a string, \"this\")");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%10s is a string", "this"));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%10s is a string", "this"));
	ft_putstr("\n");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%0s is a string", "this"));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%0s is a string", "this"));
	ft_putstr("\n");
# endif
# ifdef PRECISION
	ft_putendl("Precision: printf(\"%.5i\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%.5i", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%.5i", 42));
	ft_putstr("std:");
	printf(" (%i)\n", printf("%.5i", -42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%.5i", -42));
	ft_putstr("std:");
	printf(" (%i)\n", printf("% .5i", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("% .5i", 42));
	ft_putstr("std:");
	printf(" (%i)\n", printf("% .5i", -42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("% .5i", -42));
	ft_putstr("std:");
	printf(" (%i)\n", printf("%.2s is a string", "this"));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%.2s is a string", "this"));
	ft_putstr("\n");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%5.2s is a string", "this"));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%5.2s is a string", "this"));
	ft_putstr("\n");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%5.0s is a string", "this"));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%5.0s is a string", "this"));
	ft_putstr("\n");
# endif
# ifdef LENGTH
	ft_putendl("Length: printf(\"%hi\", 44200)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%hi", 44200));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%hi", 44200));
	ft_putstr("std:");
	printf(" (%i)\n", printf("%hhi", 44200));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%hhi", 44200));
	ft_putstr("std:");
	printf(" (%i)\n", printf("%i", 2147483650));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%i", 2147483650));
	ft_putstr("std:");
	printf(" (%i)\n", printf("%li", 2147483650));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%li", 2147483650));
	ft_putstr("std:");
	printf(" (%i)\n", printf("%lli", 9223372036854775807));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%lli", 9223372036854775807));
	ft_putstr("std:");
	printf(" (%i)\n", printf("%ji", 9223372036854775807));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%ji", 9223372036854775807));
	ft_putstr("std:");
	printf(" (%i)\n", printf("%zi", 9223372036854775807));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%zi", 9223372036854775807));
	ft_putstr("std:");
	printf(" (%i)\n", printf("%i", 9223372036854775807));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%i", 9223372036854775807));
	ft_putstr("\n");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#llx", 9223372036854775807));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#llx", 9223372036854775807));
# endif
# ifdef UNICODE
	ft_putendl("Width: printf(\"éç\")");
	printf(" (%i)\n", printf("std: éç"));
	printf(" (%i)\n", ft_printf("ft_: éç"));
	ft_putstr("\n");
# endif
# ifdef NOSPEC
	ft_putendl("printf(\"\")");
	ft_putstr("std:");
	printf("(%i)\n", printf(""));
	fflush(stdout);
	ft_putstr("ft_:");
	printf("(%i)\n", ft_printf(""));
	ft_putstr("\n");
	ft_putendl("printf(\"%%\")");
	ft_putstr("std:");
	printf("(%i)\n", printf("%%"));
	fflush(stdout);
	ft_putstr("ft_:");
	printf("(%i)\n", ft_printf("%%"));
	ft_putstr("\n");
	ft_putendl("printf(\"%5%\")");
	ft_putstr("std:");
	printf("(%i)\n", printf("%5%"));
	fflush(stdout);
	ft_putstr("ft_:");
	printf("(%i)\n", ft_printf("%5%"));
	ft_putstr("\n");
	ft_putendl("printf(\"%-5%\")");
	ft_putstr("std:");
	printf("(%i)\n", printf("%-5%"));
	fflush(stdout);
	ft_putstr("ft_:");
	printf("(%i)\n", ft_printf("%-5%"));
	ft_putstr("\n");
	ft_putendl("printf(\"%   %\")");
	ft_putstr("std:");
	printf("(%i)\n", printf("%   %"));
	fflush(stdout);
	ft_putstr("ft_:");
	printf("(%i)\n", ft_printf("%   %"));
	ft_putstr("\n");
	ft_putendl("printf(\"%+%\")");
	ft_putstr("std:");
	printf("(%i)\n", printf("%+%"));
	fflush(stdout);
	ft_putstr("ft_:");
	printf("(%i)\n", ft_printf("%+%"));
	ft_putstr("\n");
	ft_putendl("printf(\"% .3% Hello ! %% % .3%\")");
	ft_putstr("std:");
	printf("(%i)\n", printf("% .3% Hello ! %% % .3%"));
	fflush(stdout);
	ft_putstr("ft_:");
	printf("(%i)\n", ft_printf("% .3% Hello ! %% % .3%"));
	ft_putstr("\n");
# endif
# ifdef HEX
	ft_putendl("printf(\"%x\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%x", 42));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%x", 42));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%X\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%X", 42));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%X", 42));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%10x\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%10x", 42));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%10x", 42));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%-10x\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%-10x", 42));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%-10x", 42));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%#08x\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#08x", 42));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#08x", 42));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%#-08x\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#-08x", 42));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#-08x", 42));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%#8x\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#8x", 42));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#8x", 42));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%#-8x\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#-8x", 42));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#-8x", 42));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%#x\", 0)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#x", 0));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#x", 0));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%#X\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#X", 42));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#X", 42));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%#.x, %#.0x\", 0, 0)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#.x, %#.0x", 0, 0));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#.x, %#.0x", 0, 0));
	fflush(stdout);
	ft_putstr("\n");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#5.x, %#5.0x", 0, 0));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#5.x, %#5.0x", 0, 0));
	fflush(stdout);
	ft_putstr("\n");
# endif
# ifdef OCTAL
	ft_putendl("printf(\"%o\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%o", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%o", 42));
	ft_putstr("\n");
	ft_putendl("printf(\"%o\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%o", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%o", 42));
	ft_putstr("\n");
	ft_putendl("printf(\"%10o\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%10o", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%10o", 42));
	ft_putstr("\n");
	ft_putendl("printf(\"%-10o\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%-10o", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%-10o", 42));
	ft_putstr("\n");
	ft_putendl("printf(\"%#08o\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#08o", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#08o", 42));
	ft_putstr("\n");
	ft_putendl("printf(\"%#-08o\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#-08o", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#-08o", 42));
	ft_putstr("\n");
	ft_putendl("printf(\"%#8o\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#8o", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#8o", 42));
	ft_putstr("\n");
	ft_putendl("printf(\"%#-8o\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#-8o", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#-8o", 42));
	ft_putstr("\n");
	ft_putendl("printf(\"%#o\", 0)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#o", 0));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#o", 0));
	ft_putstr("\n");
	ft_putendl("printf(\"%#o\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#o", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#o", 42));
	ft_putstr("\n");
	ft_putendl("printf(\"%#.o, %#.0o\", 0, 0)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#.o, %#.0o", 0, 0));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#.o, %#.0o", 0, 0));
	ft_putstr("\n");
	ft_putendl("printf(\"%#5.o, %#5.0o\", 0, 0)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#5.o, %#5.0o", 0, 0));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#5.o, %#5.0o", 0, 0));
	ft_putstr("\n");
	ft_putendl("printf(\"%.o, %.0o\", 0, 0)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%.o, %.0o", 0, 0));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%.o, %.0o", 0, 0));
	ft_putstr("\n");
	ft_putendl("printf(\"%5.o, %5.0o\", 0, 0)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%5.o, %5.0o", 0, 0));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%5.o, %5.0o", 0, 0));
	ft_putstr("\n");
	ft_putendl("printf(\"%o\", 0)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%o", 0));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%o", 0));
	ft_putstr("\n");
# endif
# ifdef UNSIGNED
	ft_putendl("printf(\"%u\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%u", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%u", 42));
	ft_putstr("\n");
	ft_putendl("printf(\"%u\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%u", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%u", 42));
	ft_putstr("\n");
	ft_putendl("printf(\"%10u\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%10u", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%10u", 42));
	ft_putstr("\n");
	ft_putendl("printf(\"%-10u\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%-10u", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%-10u", 42));
	ft_putstr("\n");
	ft_putendl("printf(\"%#08u\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#08u", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#08u", 42));
	ft_putstr("\n");
	ft_putendl("printf(\"%#-08u\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#-08u", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#-08u", 42));
	ft_putstr("\n");
	ft_putendl("printf(\"%#8u\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#8u", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#8u", 42));
	ft_putstr("\n");
	ft_putendl("printf(\"%#-8u\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#-8u", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#-8u", 42));
	ft_putstr("\n");
	ft_putendl("printf(\"%#u\", 0)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#u", 0));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#u", 0));
	ft_putstr("\n");
	ft_putendl("printf(\"%#u\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#u", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#u", 42));
	ft_putstr("\n");
	ft_putendl("printf(\"%#.u, %#.0u\", 0, 0)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#.u, %#.0u", 0, 0));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#.u, %#.0u", 0, 0));
	ft_putstr("\n");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#5.u, %#5.0u", 0, 0));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#5.u, %#5.0u", 0, 0));
	ft_putstr("\n");
	ft_putendl("printf(\"%5u, -42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%5u", -42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%5u", -42));
	ft_putstr("\n");
	ft_putendl("printf(\"%+5u, 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%+5u", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%+5u", 42));
	ft_putstr("\n");
	ft_putendl("printf(\"%0+5u, 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%0+5u", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%0+5u", 42));
	ft_putstr("\n");
	ft_putendl("printf(\"%0+5u, -42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%0+5u", -42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%0+5u", -42));
	ft_putstr("\n");
	ft_putendl("printf(\"%05u, -42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%05u", -42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%05u", -42));
	ft_putstr("\n");
	ft_putendl("printf(\"%-05u, 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%-05u", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%-05u", 42));
	ft_putstr("\n");
	ft_putendl("printf(\"%-05u, -42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%-05u", -42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%-05u", -42));
	ft_putstr("\n");
	ft_putendl("printf(\"%-5u, -42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%-5u", -42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%-5u", -42));
	ft_putstr("\n");
	ft_putendl("printf(\"%-9.6u, 4242)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%-9.6u", 4242));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%-9.6u", 4242));
	ft_putstr("\n");
	ft_putendl("printf(\"%9.6u, 4242)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%9.6u", 4242));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%9.6u", 4242));
	ft_putstr("\n");
	ft_putendl("printf(\"%.6u, -4242)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%.6u", -4242));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%.6u", -4242));
	ft_putstr("\n");
	ft_putendl("printf(\"% 10.5u, 4242)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("% 10.5u", 4242));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("% 10.5u", 4242));
	ft_putstr("\n");
	ft_putendl("printf(\"%- 10.5u, 4242)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%- 10.5u", 4242));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%- 10.5u", 4242));
	ft_putstr("\n");
	ft_putendl("printf(\"%07.2u, 0)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%07.2u", 0));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%07.2u", 0));
	ft_putstr("\n");
	ft_putendl("printf(\"%-07.3u, -42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%-07.3u", -42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%-07.3u", -42));
	ft_putstr("\n");
	ft_putendl("printf(\"%-7.4u, -42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%-7.4u", -42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%-7.4u", -42));
	ft_putstr("\n");
	ft_putendl("printf(\"%u, -1)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%u", -1));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%u", -1));
	ft_putstr("\n");
	ft_putendl("printf(\"% u, 1)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("% u", 1));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("% u", 1));
	ft_putstr("\n");
	ft_putendl("printf(\"%lu, 4294967296)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%lu", 4294967296));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%lu", 4294967296));
	ft_putstr("\n");
	ft_putendl("printf(\"%ju, 4999999999)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%ju", 4999999999));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%ju", 4999999999));
	ft_putstr("\n");

# endif
# ifdef CHAR
	ft_putendl("printf(\"%c\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%c", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%c", 42));
	ft_putstr("\n");
	ft_putendl("printf(\"%c\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%c", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%c", 42));
	ft_putstr("\n");
	ft_putendl("printf(\"%10c\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%10c", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%10c", 42));
	ft_putstr("\n");
	ft_putendl("printf(\"%-10c\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%-10c", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%-10c", 42));
	ft_putstr("\n");
	ft_putendl("printf(\"%#08c\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#08c", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#08c", 42));
	ft_putstr("\n");
	ft_putendl("printf(\"%#-08c\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#-08c", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#-08c", 42));
	ft_putstr("\n");
	ft_putendl("printf(\"%#8c\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#8c", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#8c", 42));
	ft_putstr("\n");
	ft_putendl("printf(\"%#-8c\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#-8c", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#-8c", 42));
	ft_putstr("\n");
	ft_putendl("printf(\"%#c\", 0)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#c", 0));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#c", 0));
	ft_putstr("\n");
	ft_putendl("printf(\"%#c\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#c", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#c", 42));
	ft_putstr("\n");
	ft_putendl("printf(\"%#.c, %#.0c\", 0, 0)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#.c, %#.0c", 0, 0));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#.c, %#.0c", 0, 0));
	ft_putstr("\n");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#5.c, %#5.0c", 0, 0));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#5.c, %#5.0c", 0, 0));
	ft_putstr("\n");
	ft_putendl("printf(\"%#.2c, NULL)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#.2c", NULL));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#.2c", NULL));
	ft_putstr("\n");
	ft_putendl("printf(\"%# c, 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%# c", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%# c", 42));
	ft_putstr("\n");
	ft_putendl("printf(\"%# .3c, 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%# .3c", 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%# .3c", 42));
	ft_putstr("\n");
	ft_putendl("printf(\"%.2c, NULL)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%.2c", NULL));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%.2c", NULL));
	ft_putstr("\n");
# endif
# ifdef DIGIT
	ft_putendl("printf(\"%5d, -42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%5d", -42));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%5d", -42));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%+5d, 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%+5d", 42));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%+5d", 42));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%0+5d, 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%0+5d", 42));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%0+5d", 42));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%0+5d, -42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%0+5d", -42));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%0+5d", -42));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%05d, -42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%05d", -42));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%05d", -42));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%-05d, 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%-05d", 42));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%-05d", 42));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%-05d, -42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%-05d", -42));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%-05d", -42));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%-5d, -42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%-5d", -42));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%-5d", -42));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%-9.6d, 4242)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%-9.6d", 4242));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%-9.6d", 4242));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%9.6d, 4242)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%9.6d", 4242));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%9.6d", 4242));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%.6d, -4242)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%.6d", -4242));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%.6d", -4242));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"% 10.5d, 4242)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("% 10.5d", 4242));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("% 10.5d", 4242));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%07.2d, 0)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%07.2d", 0));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%07.2d", 0));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%i\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%i", 42));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%i", 42));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%i\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%i", 42));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%i", 42));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%10i\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%10i", 42));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%10i", 42));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%-10i\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%-10i", 42));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%-10i", 42));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%#08i\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#08i", 42));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#08i", 42));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%#-08i\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#-08i", 42));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#-08i", 42));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%#8i\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#8i", 42));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#8i", 42));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%#-8i\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#-8i", 42));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#-8i", 42));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%#i\", 0)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#i", 0));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#i", 0));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%#i\", 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#i", 42));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#i", 42));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%#.i, %#.0i\", 0, 0)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#.i, %#.0i", 0, 0));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#.i, %#.0i", 0, 0));
	fflush(stdout);
	ft_putstr("\n");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%#5.i, %#5.0i", 0, 0));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%#5.i, %#5.0i", 0, 0));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%5i, -42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%5i", -42));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%5i", -42));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%+5i, 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%+5i", 42));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%+5i", 42));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%0+5i, 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%0+5i", 42));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%0+5i", 42));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%0+5i, -42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%0+5i", -42));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%0+5i", -42));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%05i, -42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%05i", -42));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%05i", -42));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%-05i, 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%-05i", 42));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%-05i", 42));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%-05i, -42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%-05i", -42));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%-05i", -42));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%-5i, 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%-5i", 42));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%-5i", 42));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%-9.6i, 4242)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%-9.6i", 4242));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%-9.6i", 4242));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%9.6i, 4242)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%9.6i", 4242));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%9.6i", 4242));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%.6i, -4242)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%.6i", -4242));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%.6i", -4242));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"% 10.5i, 4242)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("% 10.5i", 4242));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("% 10.5i", 4242));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%07.2i, 0)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%07.2i", 0));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%07.2i", 0));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%-07.3i, -42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%-07.3i", -42));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%-07.3i", -42));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%-7.4i, -42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%-7.4i", -42));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%-7.4i", -42));
	fflush(stdout);
	ft_putstr("\n");
# endif
# ifdef UNSPEC
	ft_putendl("printf(\"%\")");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%"));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%"));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"%Z\")");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%Z"));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%Z"));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"% hZ%\")");
	ft_putstr("std:");
	printf(" (%i)\n", printf("% hZ%"));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("% hZ%"));
	fflush(stdout);
	ft_putstr("\n");
	ft_putendl("printf(\"% Z%s\", \"test\")");
	ft_putstr("std:");
	printf(" (%i)\n", printf("% Z%s", "test"));
	fflush(stdout);
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("% Z%s", "test"));
	fflush(stdout);
	ft_putstr("\n");
# endif
# ifdef HARDCORE
	
	ft_putendl("printf(\"%i, %i, %lli\", 1, 99999999999, 99999999999)");
	ft_putstr("std:\n");
	printf(" (%i)\n", printf("aaa: %i", 1));
	fflush(stdout);
	ft_putstr("ft_:\n");
	printf(" (%i)\n", ft_printf("aaa: %i", 1));
	fflush(stdout);
	ft_putendl("printf(\"%i, %i, %lli\", 1, 99999999999, 99999999999)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%i, %i, %lli", 1, 99999999999, 99999999999));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%i, %i, %lli", 1, 99999999999, 99999999999));
	ft_putstr("\n");
	ft_putendl("printf(\"%jx, %jx\", -4294967296, -4294967297)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%jx, %jx", -4294967296, -4294967297));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%jx, %jx", -4294967296, -4294967297));
	ft_putstr("\n");
	ft_putendl("printf(\"%010x, %08x\", 542, 42)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%010x, %08x", 542, 42));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%010x, %08x", 542, 42));
	ft_putstr("\n");
	ft_putendl("printf(\"%hhd, %hhd\", 128, -129)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%hhd, %hhd", 128, -129));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%hhd, %hhd", 128, -129));
	ft_putstr("\n");
	ft_putendl("printf(\"%zhd, %jhd\", 4294967296, 9223372036854775807)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%zhd, %jhd", 4294967296, 9223372036854775807));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%zhd, %jhd", 4294967296, 9223372036854775807));
	ft_putstr("\n");
	ft_putendl("printf(\"%zhd\", 4294967296)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%zhd", 4294967296));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%zhd", 4294967296));
	ft_putstr("\n");
	ft_putendl("printf(\"%jhd\", 9223372036854775807)");
	ft_putstr("std:");
	printf(" (%i)\n", printf("%jhjhd", 9223372036854775807));
	ft_putstr("ft_:");
	printf(" (%i)\n", ft_printf("%jhjhd", 9223372036854775807));
	ft_putstr("\n");

	int i = 2147483647;
	long l = 2147483647;
	long long ll = 9223372036854775807;
	char c = 0;
	intmax_t im = 9223372036854775807;

	setlocale(LC_ALL, "fr_FR.UTF-8");
	//setlocale(LC_ALL, "en_US.UTF-8");
	//setlocale(LC_ALL, "");
	printf("\n");
	fflush(stdout);
	ft_printf("\n");
	printf("%%\n");
	fflush(stdout);
	ft_printf("%%\n");
	printf("%d\n", 42);
	fflush(stdout);
	ft_printf("%d\n", 42);
	printf("%d%d\n", 42, 41);
	fflush(stdout);
	ft_printf("%d%d\n", 42, 41);
	printf("%d%d%d\n", 42, 43, 44);
	fflush(stdout);
	ft_printf("%d%d%d\n", 42, 43, 44);
	printf("%ld\n", l);
	fflush(stdout);
	ft_printf("%ld\n", l);
	printf("%lld\n", ll);
	fflush(stdout);
	ft_printf("%lld\n", ll);
	printf("%x %X %p %20.15d\n", 505, 505, &ll, 54321);
	fflush(stdout);
	ft_printf("%x %X %p %20.15d\n", 505, 505, &ll, 54321);
	ft_putstr("0 std: ");
	printf("%-10d % d %+d %010d %hhd\n", 3, 3, 3, 1, c);
	fflush(stdout);
	ft_putstr("0 ft_: ");
	ft_printf("%-10d % d %+d %010d %hhd\n", 3, 3, 3, 1, c);
	ft_putstr("1 std: ");
	printf("%jd %zd %u %o %#08x\n", im, (size_t)i, i, 40, 42);
	fflush(stdout);
	ft_putstr("1 ft_: ");
	ft_printf("%jd %zd %u %o %#08x\n", im, (size_t)i, i, 40, 42);
	ft_putstr("2 std: ");
	printf(" (%i)\n", printf("%x %#X %S %s%s", 1000, 1000, L"ݗݜशব", "test", "test2"));
	fflush(stdout);
	ft_putstr("2 ft_: ");
	printf(" (%i)\n", ft_printf("%x %#X %S %s%s", 1000, 1000, L"ݗݜशব", "test", "test2"));
	ft_putstr("3 std: ");
	printf(" (%i)\n", printf("%s%s%s", "test", "test", "test"));
	fflush(stdout);
	ft_putstr("3 ft_: ");
	printf(" (%i)\n", ft_printf("%s%s%s", "test", "test", "test"));
	ft_putstr("4 std: ");
	printf(" (%i)\n", printf("%c", 75));
	fflush(stdout);
	ft_putstr("4 ft_: ");
	printf(" (%i)\n", ft_printf("%c", 75));
	ft_putstr("4 std: ");
	printf(" (%i)\n", printf("%C", 8000));
	fflush(stdout);
	ft_putstr("4 ft_: ");
	printf(" (%i)\n", ft_printf("%C", 8000));
	ft_putstr("5 std: ");
	printf(" (%i)\n", printf("%C", 80000));
	fflush(stdout);
	ft_putstr("5 ft_: ");
	printf(" (%i)\n", ft_printf("%C", 80000));
	ft_putstr("6 std: ");
	printf(" (%i)\n", printf("%C", L'α'));
	fflush(stdout);
	ft_putstr("6 ft_: ");
	printf(" (%i)\n", ft_printf("%C", L'α'));
	ft_putstr("7 std: ");
	printf(" (%i)\n", printf("%s, %s", "Hello les cocos !", NULL));
	fflush(stdout);
	ft_putstr("7 ft_: ");
	printf(" (%i)\n", ft_printf("%s, %s", "Hello les cocos !", NULL));
	printf(" (%i)\n", printf("%-11.3s, %-11.6s", "Hello les cocos !", NULL));
	printf(" (%i)\n", ft_printf("%-11.3s, %-11.6s", "Hello les cocos !", NULL));
	printf(" (%i)\n", printf("%-11.3s, %-11.0s", "Hello les cocos !", NULL));
	printf(" (%i)\n", ft_printf("%-11.3s, %-11.0s", "Hello les cocos !", NULL));
	printf(" (%i)\n", printf("%-3.11s, %-3.11s", "Hello les cocos !", NULL));
	printf(" (%i)\n", ft_printf("%-3.11s, %-3.11s", "Hello les cocos !", NULL));
	printf(" (%i)\n", printf("%-s, %-s", "Hello les cocos !", NULL));
	printf(" (%i)\n", ft_printf("%-s, %-s", "Hello les cocos !", NULL));

	printf(" (%i)\n", printf("%4C%4C%4C%4C", L'ݗ', L'ݜ', L'श', L'ব'));
	fflush(stdout);
	printf(" (%i)\n", ft_printf("%4C%4C%4C%4C", L'ݗ', L'ݜ', L'श', L'ব'));
	ft_putstr("X std: ");
	printf(" (%i)\n", printf("%x %#X %-17S %s%s", 1000, 1000, L"ݗݜशবݜ", "test", "test2"));
	fflush(stdout);
	ft_putstr("X ft_: ");
	printf(" (%i)\n", ft_printf("%x %#X %-17S %s%s", 1000, 1000, L"ݗݜशবݜ", "test", "test2"));
	ft_putstr("X std: ");
	printf(" (%i)\n", printf("%x %#X %-17S %s%s", 1000, 1000, L"বशݜݗ", "test", "test2"));
	fflush(stdout);
	ft_putstr("X ft_: ");
	printf(" (%i)\n", ft_printf("%x %#X %-17S %s%s", 1000, 1000, L"বशݜݗ", "test", "test2"));
	ft_putstr("X std: ");
	printf(" (%i)\n", printf("%x %#X % 017.9S %s%s", 1000, 1000, L"ݗݜशব", "test", "test2"));
	fflush(stdout);
	ft_putstr("X ft_: ");
	printf(" (%i)\n", ft_printf("%x %#X % 017.9S %s%s", 1000, 1000, L"ݗݜशব", "test", "test2"));
	ft_putstr("X std: ");
	printf(" (%i)\n", printf("%x %#X %4.2S %s%s", 1000, 1000, L"ݗݜशব", "test", "test2"));
	fflush(stdout);
	ft_putstr("X ft_: ");
	printf(" (%i)\n", ft_printf("%x %#X %4.2S %s%s", 1000, 1000, L"ݗݜशব", "test", "test2"));
	ft_putstr("X std: ");
	printf(" (%i)\n", printf("%x %#X %-17.11S %s%s", 1000, 1000, L"ݗݜशবݜ", "test", "test2"));
	fflush(stdout);
	ft_putstr("X ft_: ");
	printf(" (%i)\n", ft_printf("%x %#X %-17.11S %s%s", 1000, 1000, L"ݗݜशবݜ", "test", "test2"));
	ft_putstr("X std: ");
	printf(" (%i)\n", printf("%x %#X %97.35S %s%s", 1000, 1000, L"uèéeêëēėęOবशݜݗèéeêëēėęO", "test", "test2"));
	fflush(stdout);
	ft_putstr("X ft_: ");
	printf(" (%i)\n", ft_printf("%x %#X %97.35S %s%s", 1000, 1000, L"uèéeêëēėęOবशݜݗèéeêëēėęO", "test", "test2"));
# endif
# ifdef MOULITEST
	setlocale(LC_ALL, "fr_FR.UTF-8");
	printf("1- %.c\n", 0);
	fflush(stdout);
	ft_printf("1- %.c\n", 0);
	printf("2- %.5c\n", 0);
	fflush(stdout);
	ft_printf("2- %.5c\n", 0);
	printf("3- %.5c\n", 42);
	fflush(stdout);
	ft_printf("3- %.5c\n", 42);
	printf("4- %.C\n", 0);
	fflush(stdout);
	ft_printf("4- %.C\n", 0);
	printf("5- %.5C\n", 0);
	fflush(stdout);
	ft_printf("5- %.5C\n", 0);
	printf("6- %.5C\n", 42);
	fflush(stdout);
	ft_printf("6- %.5C\n", 42);
	ft_printf("============\n");
	printf("7- {%5p}\n",  0);
	fflush(stdout);
	ft_printf("7- {%5p}\n", 0);
	printf("8- {%-15p}\n", 0);
	fflush(stdout);
	ft_printf("8- {%-15p}\n", 0);
	printf("9- {%10RN}\n");
	fflush(stdout);
	ft_printf("9- {%10RN}\n");
	printf( " (%i)\n", printf("10- {%30S}", L"我是一只猫。"));
	fflush(stdout);
	printf( " (%i)\n", ft_printf("10- {%30S}", L"我是一只猫。"));
	fflush(stdout);
	printf( " (%i)\n", printf("11- {%-30S}", L"我是一只猫。"));
	fflush(stdout);
	printf( " (%i)\n", ft_printf("11- {%-30S}", L"我是一只猫。"));
	fflush(stdout);
	ft_printf("============\n");
	printf( " (%i)\n", printf("1- %.0p, %.p", 0, 0));
	fflush(stdout);
	printf( " (%i)\n", ft_printf("1- %.0p, %.p", 0, 0));
	fflush(stdout);
	printf( " (%i)\n", printf("2- %.5p", 0));
	fflush(stdout);
	printf( " (%i)\n", ft_printf("2- %.5p", 0));
	fflush(stdout);
	printf( " (%i)\n", printf("3- %9.2p", 1234));
	fflush(stdout);
	printf( " (%i)\n", ft_printf("3- %9.2p", 1234));
	fflush(stdout);
	printf( " (%i)\n", printf("4- %9.2p", 1234567));
	fflush(stdout);
	printf( " (%i)\n", ft_printf("4- %9.2p", 1234567));
	fflush(stdout);
	printf( " (%i)\n", printf("5- %2.9p", 1234));
	fflush(stdout);
	printf( " (%i)\n", ft_printf("5- %2.9p", 1234));
	fflush(stdout);
	printf( " (%i)\n", printf("6- %2.9p", 1234567));
	fflush(stdout);
	printf( " (%i)\n", ft_printf("6- %2.9p", 1234567));
	fflush(stdout);
	ft_printf("============\n");
	printf("Haha: % s %C, % s, % s, ok.\n", "hello", L'該', NULL, "");
	ft_printf("Haha: % s %C, % s, % s, ok.\n", "hello", L'該', NULL, "");
	printf( " (%i)\n", printf("%s %C %d %p %x %% %S", "bonjour ", L'該', 42, &free, 42, L"لحم خنزير"));
	fflush(stdout);
	printf( " (%i)\n", ft_printf("%s %C %d %p %x %% %S", "bonjour ", L'該', 42, &free, 42, L"لحم خنزير"));
	/*
	char c;
	fflush(stdout);
	printf( " (%i)\n", printf("%s%d%p%%%S%D%i%o%O%u%U%x%X%c%C","bonjour", 42, &c, L"暖炉", LONG_MAX, 42, 42, 42, 100000, ULONG_MAX, 42, 42, 'c', L'플'));
	fflush(stdout);
	printf( " (%i)\n", ft_printf("%s%d%p%%%S%D%i%o%O%u%U%x%X%c%C", "bonjour", 42, &c, L"暖炉", LONG_MAX, 42, 42, 42, 100000, ULONG_MAX, 42, 42, 'c', L'플'));
	fflush(stdout);
	*/
	printf( " (%i)\n", printf("% p|%+p", 42, 42));
	fflush(stdout);
	printf( " (%i)\n", ft_printf("% p|%+p", 42, 42));
	fflush(stdout);
	printf(" (%i)\n", printf("{% s}", NULL));
	fflush(stdout);
	printf(" (%i)\n", ft_printf("{% s}", NULL));
	fflush(stdout);
	printf(" (%i)\n", printf("{% s}", "(null)"));
	fflush(stdout);
	printf(" (%i)\n", ft_printf("{% s}", "(null)"));
	fflush(stdout);
	printf(" (%i)\n", printf("{% s}", ""));
	fflush(stdout);
	printf(" (%i)\n", ft_printf("{% s}", ""));
	fflush(stdout);
	printf(" (%i)\n", printf("{% S}", NULL));
	fflush(stdout);
	printf(" (%i)\n", ft_printf("{% S}", NULL));
	fflush(stdout);
	printf(" (%i)\n", printf("%#.3o", 1));
	fflush(stdout);
	printf(" (%i)\n", ft_printf("%#.3o", 1));
	fflush(stdout);
	printf(" (%i)\n", printf("{%+05.S}", L"42 c est cool"));
	fflush(stdout);
	printf(" (%i)\n", ft_printf("{%+05.S}", L"42 c est cool"));
	fflush(stdout);

	printf(" (%i)\n", printf("%+o", 0));
	fflush(stdout);
	printf(" (%i)\n", ft_printf("%+o", 0));
	fflush(stdout);
	printf(" (%i)\n", printf("%+o", 42));
	fflush(stdout);
	printf(" (%i)\n", ft_printf("%+o", 42));
	fflush(stdout);
	printf(" (%i)\n", printf("%+O", 0));
	fflush(stdout);
	printf(" (%i)\n", ft_printf("%+O", 0));
	fflush(stdout);
	printf(" (%i)\n", printf("%+O", 42));
	fflush(stdout);
	printf(" (%i)\n", ft_printf("%+O", 42));
	fflush(stdout);
	printf(" (%i)\n", printf("[%+s]", 0));
	fflush(stdout);
	printf(" (%i)\n", ft_printf("[%+s]", 0));
	fflush(stdout);
	printf(" (%i)\n", printf("[%+s]", "(null)"));
	fflush(stdout);
	printf(" (%i)\n", ft_printf("[%+s]", "(null)"));
	fflush(stdout);
	printf(" (%i)\n", printf("%+O", 1));
	fflush(stdout);
	printf(" (%i)\n", ft_printf("%+O", 1));
	fflush(stdout);
	printf(" (%i)\n", printf("%hhx, %hhx", 0, UCHAR_MAX + 42));
	fflush(stdout);
	printf(" (%i)\n", ft_printf("%hhx, %hhx", 0, UCHAR_MAX + 42));
	fflush(stdout);
	printf(" (%i)\n", printf("%hhX, %hhX", 0, UCHAR_MAX + 42));
	fflush(stdout);
	printf(" (%i)\n", ft_printf("%hhX, %hhX", 0, UCHAR_MAX + 42));
	fflush(stdout);
	printf(" (%i)\n", printf("% o|%+o", 42, 42));
	fflush(stdout);
	printf(" (%i)\n", ft_printf("% o|%+o", 42, 42));
	fflush(stdout);
	printf(" (%i)\n", printf("% x|%+x", 42, 42));
	fflush(stdout);
	printf(" (%i)\n", ft_printf("% x|%+x", 42, 42));
	fflush(stdout);
	printf(" (%i)\n", printf("% X|%+X", 42, 42));
	fflush(stdout);
	printf(" (%i)\n", ft_printf("% X|%+X", 42, 42));
	fflush(stdout);
	printf(" (%i)\n", ft_printf("% o|%+o", 42, 42));
	fflush(stdout);
	printf(" (%i)\n", ft_printf("% o|%+o", 42, 42));
	fflush(stdout);
	printf(" (%i)\n", printf("{%05p}", 0));
	fflush(stdout);
	printf(" (%i)\n", ft_printf("{%05p}", 0));
	fflush(stdout);
	printf(" (%i)\n", printf("{%5p}", 0));
	fflush(stdout);
	printf(" (%i)\n", ft_printf("{%5p}", 0));
	fflush(stdout);
# endif
#else

	// sS  string of characters
	// p   pointer address
	// dD  signed decimal integer
	// i   signed decimal integer
	// oO  unsigned octal
	// uU  unsigned decimal integer
	// xX  unsigned hexadecimal integer lowercase / uppercase
	// cC  character
	printf("Hello\n");
	ft_printf("Hello\n");

#endif

	return (0);
}
